modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
modId="linkingbooks"
version="0.1.0"
displayName="Linking Books"
description='''
Teleport via linking books from the iconic Myst universe.
'''

[[dependencies.linkingbooks]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.linkingbooks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"